### ISSUE TITLE
Cannot be used in PCL library in Xamarin Studio

### ISSUE THREAD

**Issue by MarcoMiltenburg** [abjerner/Skybrud.Colors#1]
Was looking for a small and simple library like this but can't add this as a package to my PCL library in Xamarin Studio. I get the following error:

```
Attempting to gather dependency information for package 'Skybrud.Colors.1.0.1' with respect to project 'XXXXX', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
Attempting to resolve dependencies for package 'Skybrud.Colors.1.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Skybrud.Colors.1.0.1'
Resolved actions to install package 'Skybrud.Colors.1.0.1'
For adding package 'Skybrud.Colors.1.0.1' to project 'XXXXX' that targets 'portable45-net45+win8+wpa81'.
Install failed. Rolling back...
Package 'Skybrud.Colors.1.0.1' does not exist in project 'XXXXX'
Package 'Skybrud.Colors.1.0.1' does not exist in folder '/Users/Marco/Projects/XXXXX/app/YYYYY/packages'
Could not install package 'Skybrud.Colors 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by abjerner** [comment]
I'm usually building either ASP.NET and console applications, and thereby targeting the full .NET framework.

I don't really know that much about creating PLC libraries. Would changing the project type from **Class library** to **Class library (Portable)** be sufficient? Or do I need to do something specific to support Xamarin?

**Comment by MarcoMiltenburg** [comment]
To be honest, I'm pretty new to Xamarin and PCL as well. I will create a fork and experiment.

**Comment by abjerner** [comment]
@MarcoMiltenburg I forgot about this one, but also still really don't know much about PLC. Is it still an issue, or did you find another to solve your problem?
